### ISSUE TITLE
GStreamer OpenGL ES Rendering

### ISSUE THREAD

**Issue by rsavignon** [jumpnow/meta-jumpnow#1]
Hi all,
i don't know if this is the most appropriate repository, but i am facing a problem regarding showing video frames in a OpenGL ES window on the new dunfell branch. This was working on zeus branch, but i had to upgrade due qt version requirement.

Raspberry pi 3 Model b

`gst-launch-1.0  videotestsrc ! glimagesink`

When i execute the above  test command i get a error message like this:

`Setting pipeline to PAUSED ...
0:00:00.283948213 10169  0x1ffdb40 WARN             glimagesink gstglimagesink.c:1010:_ensure_gl_setup:<sink> error: glGetString not defined or returned invalid value
ERROR: Pipeline doesn't want to pause.
Got context from element 'sink': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayEGL\)\ gldisplayegl0";
ERROR: from element /GstPipeline:pipeline0/GstGLImageSinkBin:glimagesinkbin0/GstGLImageSink:sink: glGetString not defined or returned invalid value
Additional debug info:
../gst-plugins-base-1.16.2/ext/gl/gstglimagesink.c(1010): _ensure_gl_setup (): /GstPipeline:pipeline0/GstGLImageSinkBin:glimagesinkbin0/GstGLImageSink:sink
Setting pipeline to NULL ...
Freeing pipeline ...
`

I certified myself that libbrcmGLESv2.so had the glGetString with the command :
`
nm -gDC /usr/lib/libbrcmGLESv2.so
`

0000e080 T glGetShaderPrecisionFormat
0000d234 T glGetShaderSource
0000d0a0 T glGetShaderiv
00008810 T glGetString
000089bc T glGetTexEnvfv
0000890c T glGetTexEnviv

And set GL_VERSION environment variable to some value.

`
export GL_VERSION='2.1'
`

Thanks in advance.

**Comment by scottellis** [comment]
Hi Rafael,

This is not the correct place to report a bug like this.

I am not a gstreamer user.

Best regards,
Scott


"Rafael Savignon Marinho" <notifications@github.com> said:

**Comment by rsavignon** [comment]
Sorry Scott,
i'm using jumpnow yocto meta layers to build rpi3 images. On the zeus branch the command was executed successful and a window popped up, but with dunfell branch it doesn't. By the way, congratulations for excellent work on yocto meta layers.
